import { Injectable } from '@angular/core';
import { Category } from '../models/category.model';
import { Product } from '../models/product.model';

@Injectable({ providedIn: 'root' })
export class ProductService {
  private categories: Category[] = [
    { id: 1, name: 'Sports & Outdoors' },
    { id: 2, name: 'Office & School' },
    { id: 3, name: 'Electronics' },
    { id: 4, name: 'Home & Furniture' },
  ];

  private products: Product[] = [
    //Sports
    {
      id: 1,
      name: 'Велосипед Petava BMX',
      description: 'Велосипед Petava BMX-3 PT-216S 2023',
      price: 68000,
      rating: 4.7,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p1d/p4f/42747506.png',
      link: 'https://kaspi.kz/shop/p/velosiped-petava-bmx-3-pt-216s-112591119/',
      likes: 0,
      categoryId: 1,
    },
    {
      id: 2,
      name: 'Скакалка со счетчиком',
      description: 'Скакалка для фитнеса с электронным счетчиком',
      price: 3990,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h53/hfb/64319651676190.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/skakalka-so-schetchikom-101633252/',
      likes: 0,
      categoryId: 1,
    },
    {
      id: 3,
      name: 'Коврик для йоги',
      description: 'Коврик для йоги и фитнеса 173x61 см',
      price: 2990,
      rating: 4.5,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h5d/h04/64158004740126.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/yoga-mat-106126385/',
      likes: 0,
      categoryId: 1,
    },
    {
      id: 4,
      name: 'Гантель 5 кг',
      description: 'Неразборная гантель 5 кг',
      price: 9990,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/hb8/h00/65051467579422.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/gantel-5-kg-107333392/',
      likes: 0,
      categoryId: 1,
    },
    {
      id: 5,
      name: 'Футбольный мяч',
      description: 'Футбольный мяч ATEMI размер 4',
      price: 7990,
      rating: 4.7,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h9b/hc7/82092024365086.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/mjach-futbol-nyi-111971786/',
      likes: 0,
      categoryId: 1,
    },

    // Office
    {
      id: 6,
      name: 'Ластик Maped',
      description: 'Ластик Maped Technic Duo',
      price: 10,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h56/h80/86018938044446.jpg',
      link: 'https://kaspi.kz/shop/p/lastik-maped-103885134/',
      likes: 0,
      categoryId: 2,
    },
    {
      id: 7,
      name: 'Тетрадь A5',
      description: 'Тетрадь 96 листов, клетка',
      price: 490,
      rating: 4.6,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/he7/h19/87108655972382.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/tetrad-96-listov-123511511/',
      likes: 0,
      categoryId: 2,
    },
    {
      id: 8,
      name: 'Степлер',
      description: 'Степлер под скобы №10',
      price: 790,
      rating: 4.7,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h1e/ha1/84574232346654.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/stepler-114855400/',
      likes: 0,
      categoryId: 2,
    },
    {
      id: 9,
      name: 'Набор ручек',
      description: 'Ручка + карандаш',
      price: 19990,
      rating: 4.8,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pc6/p49/47006403.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/nabor-ruchek-140917496/',
      likes: 0,
      categoryId: 2,
    },
    {
      id: 10,
      name: 'Рюкзак',
      description: 'Школьный рюкзак, 3 отделения',
      price: 7990,
      rating: 4.7,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p61/p67/12554045.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/rjukzak-131245878/',
      likes: 0,
      categoryId: 2,
    },

    //electronka
    {
      id: 11,
      name: 'Кофемашина DeLonghi',
      description: 'Автоматическая кофемашина',
      price: 229000,
      rating: 4.6,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p6b/pfe/63494146.jpg',
      link: 'https://kaspi.kz/shop/p/kofemashina-delonghi-145399057/',
      likes: 0,
      categoryId: 3,
    },
    {
      id: 12,
      name: 'Мышь Logitech G102',
      description: 'Игровая мышь до 8000 DPI',
      price: 6870,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/hb2/hc2/64119540187166.jpg',
      link: 'https://kaspi.kz/shop/p/logitech-g102-100956618/',
      likes: 0,
      categoryId: 3,
    },
    {
      id: 13,
      name: 'Крепление для монитора',
      description: 'NB F80, настольное',
      price: 7746,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h37/hf5/81272594268190.png',
      link: 'https://kaspi.kz/shop/p/nb-f80-110855908/',
      likes: 0,
      categoryId: 3,
    },
    {
      id: 14,
      name: 'Wi-Fi роутер TP-LINK',
      description: 'Wi-Fi до 300 Мбит/с',
      price: 11370,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pcf/p1e/104875831.jpg',
      link: 'https://kaspi.kz/shop/p/tp-link-td-w8961n-7600132/',
      likes: 0,
      categoryId: 3,
    },
    {
      id: 15,
      name: 'Клавиатура Logitech K120',
      description: 'Проводная клавиатура USB',
      price: 4990,
      rating: 4.8,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p86/p08/35485439.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/logitech-k120-9200076/',
      likes: 0,
      categoryId: 3,
    },

    //Home
    {
      id: 16,
      name: 'Распашной шкаф',
      description: 'Шкаф 120x190 см',
      price: 62900,
      rating: 4.8,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p4f/pd8/83121137.png',
      link: 'https://kaspi.kz/shop/p/shkaf-106553991/',
      likes: 0,
      categoryId: 4,
    },
    {
      id: 17,
      name: 'Полка',
      description: 'Полка настенная',
      price: 2250,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h22/h0e/86932684308510.jpg',
      link: 'https://kaspi.kz/shop/p/polka-110810653/',
      likes: 0,
      categoryId: 4,
    },
    {
      id: 18,
      name: 'Стул',
      description: 'Стул для кухни',
      price: 10470,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h05/hd2/64515775430686.jpg',
      link: 'https://kaspi.kz/shop/p/stul-106633022/',
      likes: 0,
      categoryId: 4,
    },
    {
      id: 19,
      name: 'Настольная лампа',
      description: 'LED лампа',
      price: 5990,
      rating: 4.6,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h21/h09/86739183140894.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/lampa-122207391/',
      likes: 0,
      categoryId: 4,
    },
    {
      id: 20,
      name: 'Постельное белье',
      description: 'Комплект 1.5-спальный',
      price: 6990,
      rating: 4.5,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pc2/p44/34850139.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/postel-noe-bele-137605534/',
      likes: 0,
      categoryId: 4,
    },
  ];

  getCategories(): Category[] {
    return this.categories;
  }

  getProductsByCategory(categoryId: number): Product[] {
    return this.products.filter(p => p.categoryId === categoryId);
  }
}
